In [1]:
#################
#PACKAGE IMPORTS#
import pandas as pd
import numpy as np
import pathlib
import re

In [13]:
#For each data sub folder, iterate through and set 
#all files together into a dingle dataframe
table_type = 'Key_Stats'
folder = pathlib.Path(f"./data/{table_type}")

file_list_path = list(folder.rglob("*.csv"))
#Remove directories prior to the file
#by replaceing anything prior to '\\'
#with empty string
file_list = [re.sub('^.*\\\\','',value.__str__()) for value in file_list_path]

#Load the first data frame which will be concatenated
#Remove first two columns since no longer relevant
df_main = pd.read_csv(f"./data/{table_type}/"+file_list[0]).iloc[:,2:]
df_main.columns = [col.strip() for col in df_main.columns]
#Set the data together
for file in file_list[1:]:
    #Load in next file
    df_temp = pd.read_csv(f"./data/{table_type}/"+file).iloc[:,2:]
    df_temp.columns = [col.strip() for col in df_temp.columns]
    #Concatenate together
    df_main = pd.concat([df_main, df_temp], ignore_index=True)

In [14]:
df_main

,Player,Position,AF,R,G,D,M,T,C,K,H,HO,Season,Round
0,Joel Corey,MID,110,10.0,0,22,3,12,4,10,12,0,2012,Finals Week 1
1,Michael Barlow,MID,127,6.3,0,27,6,11,2,12,15,0,2012,Finals Week 1
2,Jimmy Bartel,MID,111,9.6,0,26,5,8,5,13,13,0,2012,Finals Week 1
3,Paul Chapman,FWD,88,12.0,0,20,1,8,4,14,6,0,2012,Finals Week 1
4,Chris Mayne,FWD,90,10.8,0,16,5,8,0,11,5,0,2012,Finals Week 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109914,Nasiah Wanganeen-Milera,DEF,49,0.0,0,15,3,0,2,13,2,0,2024,Round 1
109915,Jacob Wehr,MID,54,2.8,0,14,5,0,0,10,4,0,2024,Round 1
109916,Callum Wilkie,KEYD,39,0.0,0,9,5,0,0,6,3,0,2024,Round 1
109917,Lewis Young,KEYD,71,8.3,0,17,9,0,0,13,4,1,2024,Round 1
109918,Tylar Young,KEYD,8,3.4,0,3,0,0,0,2,1,0,2024,Round 1

In [12]:
df_main.columns

Index(['Rank', 'Player', 'Position', 'AF', 'R', 'G', 'D', 'M', 'T', 'C', 'K',
       'H', 'HO', 'Season', 'Round'],
      dtype='object')

In [15]:
string = "Key Stats"

In [16]:
re.sub(r'\s','_',string)

'Key_Stats'

In [17]:
a = set([1,2,3,4,5])
b = set([7,6,5,4])

a&b

{4, 5}

In [20]:
#Delete no longer needed dataframes
del df_main
del df_temp
############################################ 
#Joining the Player Data for Unique Features
#Extract list of combined data csv files from the data folder
folder = pathlib.Path(f"./data") 
file_list_path = list(folder.rglob("combined*.csv")) 
file_list = [re.sub('^.*\\\\','',value.__str__()) for value in file_list_path]

#Define function to determine common columns
def common_member(df1, df2):
    df1_set = set(df1.columns)
    df2_set = set(df2.columns)
 
    if (df1_set & df2_set):
        #Create a list for all columns except for join conditions
        #of 'Player', 'Season', 'Round'
        common_cols = list(df1_set&df2_set - {'Player','Season','Round'})    
    else:
        common_cols = []
    return common_cols

#Load the first data frame which will be joined
df_main = pd.read_csv(f"./data/"+file_list[0],index_col=0)

#Join data one after the other until all data is present in one table for players
for file in file_list[1:]:
        #Load in next file
        df_temp = pd.read_csv(f"./data/"+file,index_col=0)
        #Obtain column columns prior to join
        common_cols = common_member(df_main,df_temp)
        if len(common_cols) > 0:
             df_temp = df_temp.drop(common_cols, axis=1)
        
        #Join together
        df_main = df_main.merge(df_temp, on=['Player','Season','Round'], how='left')

In [21]:
df_main

,Player,Position,T,Ti50,PA,DHPA,S,CDOOO,CDL,CDL%,...,GA%,SAG,SI,SL,CC,SC,HTA,HTW%,HTA%,RC
0,Joel Corey,MID,12,0,24,11,0,0,0,0.0,...,0.0,0,3,1,2,2,0,0.0,0.0,0
1,Michael Barlow,MID,11,3,27,14,2,0,0,0.0,...,0.0,1,4,0,1,1,0,0.0,0.0,0
2,Jimmy Bartel,MID,8,1,17,9,1,0,0,0.0,...,0.0,1,4,0,1,4,0,0.0,0.0,0
3,Paul Chapman,FWD,8,3,20,5,2,0,0,0.0,...,0.0,1,3,1,1,3,0,0.0,0.0,0
4,Chris Mayne,FWD,8,4,19,8,0,0,0,0.0,...,0.0,1,2,1,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109914,Nasiah Wanganeen-Milera,DEF,0,0,0,0,0,0,0,0.0,...,0.0,0,0,0,0,2,0,0.0,0.0,0
109915,Jacob Wehr,MID,0,0,11,7,0,0,0,0.0,...,0.0,1,7,1,0,0,0,0.0,0.0,0
109916,Callum Wilkie,KEYD,0,0,0,0,0,0,0,0.0,...,0.0,0,2,0,0,0,0,0.0,0.0,0
109917,Lewis Young,KEYD,0,0,3,2,6,3,2,66.7,...,0.0,0,2,2,0,0,1,100.0,100.0,1
109918,Tylar Young,KEYD,0,0,1,1,3,0,0,0.0,...,0.0,0,0,0,0,0,0,0.0,0.0,0

In [24]:
df_main.columns

Index(['Player', 'Position', 'T', 'Ti50', 'PA', 'DHPA', 'S', 'CDOOO', 'CDL',
       'CDL%', 'Season', 'Round', 'D', 'K', 'H', 'i50s', 'DE%', 'C', 'R50s',
       'EK', 'KE%', 'KHB', 'ED', 'FF', 'FA', 'AF', 'B', 'OP', 'ToG%', 'R', 'G',
       'M', 'HO', 'Mi50', 'CM', 'MOL', 'IM', 'CP', 'UP', 'IP', 'CPR', 'GBG',
       'F50GBG', 'GA', 'GA%', 'SAG', 'SI', 'SL', 'CC', 'SC', 'HTA', 'HTW%',
       'HTA%', 'RC'],
      dtype='object')